### ISSUE TITLE
Leica compressed/uncompressed

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#15]
For leica, there is no differentiation between compressed and uncompressed raw files.
https://raw.pixls.us/getfile.php?type=exif&id=752
https://raw.pixls.us/getfile.php?type=exif&id=753

diff points at 
```diff
-Exif.SubImage1.BitsPerSample                  8
+Exif.SubImage1.BitsPerSample                  16
```

**Comment by LebedevRI** [comment]
This should also be added to the list next to `Canon: RAW, mRAW, sRAW.`
I wonder if the system should always consider bitness and compression tags

**Comment by andabata** [comment]
Support is added for Leica.
