### ISSUE TITLE
CHDK

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#20]
next to Pentax: Both PEF and DNG.
there should be a line: `Canon CHDK: both the old-style CRW, and new DNG`
or something like that

**Comment by andabata** [comment]
Only CHDK, or the other alternative firmwares aswell (Magic Lantern/PTool/Nikon Hacker) ?

**Comment by LebedevRI** [comment]
Magic Lantern - no, at least not yet.
i'll let others who know answer about the rest :)
