### ISSUE TITLE
checksum text

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#21]
https://raw.pixls.us/getfile.php?type=sha1sum&id=129 asks me where to save it.
surely the checksum is just a text string which can be displayed in browser

**Comment by patdavid** [comment]
I fixed the link to display the text in the browser, but now I'm wondering if the checksum data might look better (or be better used) if it were included in the same cell as the file, but underneath the file link?

![checksum example](http://i.imgur.com/avU4rwQ.png)

**Comment by LebedevRI** [comment]
And maybe that same column should contain the raw's size, in mbytes without kbytes
