### ISSUE TITLE
Better sync methods

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#25]
Is there any better way than just downloading the whole archive?

**Comment by andabata** [comment]
Sure, any thoughs on what you envision ? Their are loads of options to create something like that, however i do prefer something webbased.

**Comment by patdavid** [comment]
Isn't it fairly standard to use something like rsync to mirror repositories?  I know it'd be the first tool I would look for if I was going to mirror all these files.  Of course, if we can keep things alive and fast, there might not be a need for mirroring. ;)

**Comment by paperdigits** [comment]
Rsync is fairly standard, but the server would need to run an rsync daemon to allow access. Zsync uses librsync, but works over http, the server needs  to provide manifest of files. There is also lftp -mirror.

**Comment by andabata** [comment]
Just to outline the reasons i've not yet come up with a working solution:
- Data is stored out of the webroot to prevent abuse (to prevent accidently hosting of malware/warez and such)
- Data is stored in a hashed data structure which doesn't make sense for any one else ( ../data/1/2/3/321/IMG_3332.CR2)

I could create a public datadir with symlinks pointing to the actuall files. But that creates another challenge.
How to create a directory/file structure that makes sense for someone else.
I could make a structure like /exifmake/exifmodel/filename.raw, but exifmake/exifmodel aren't consistenly used by manufactures eg for nikon allone there is:
Nikon, NIKON, NIKON CORPORATION. With model naming even more disorganized.

It's not that it's impossible to create something, but more that i just don't know at this moment a solution that makes sense.
January 7, 2017 2:47 AM, "Mica"  wrote:
Rsync is fairly standard, but the server would need to run an rsync daemon to allow access. Zsync uses librsync, but works over http, the server needs to provide manifest of files. There is also lftp -mirror.

**Comment by paperdigits** [comment]
Perhaps just having a good index of all the files would be helpful; a CSV file or make/model, etc?

**Comment by andabata** [comment]
I just added a publicdatadir, which is hourly build. (they are symlinks). Rawspeeds cameras.xml is used for naming the make and model.  Strange namings occur when they are missing in the cameras.xml

https://raw.pixls.us/data/

You should be able to mirror that with lftp or wget

**Comment by LebedevRI** [comment]
> Strange namings occur when they are missing in the cameras.xml

I'll attempt to fix all the currently missing manglings tomorrow, unless someone beats me to it :)

**Comment by LebedevRI** [comment]
Awesome!
Following command seems to do what i want:
```bash
lftp -c mirror -c -P 4 -v --delete --dry-run https://raw.pixls.us/data/ ~/raw-camera-samples/raw.pixls.us
```
Remove `--dry-run` once you have **verified** that it does what you want it to do.

**Comment by axxel** [comment]
For what it's worth: it seems everything after `mirror` has to escaped in quotes. This works for me:

```
lftp -c mirror "-c -P 4 -v --delete --dry-run --exclude-glob=\*.hash\* https://raw.pixls.us/data/ ~/raw-camera-samples/raw.pixls.us"
```

**Comment by LebedevRI** [comment]
Hm, seems to work fine for me without `"`

**Comment by axxel** [comment]
Maybe an issue with my outdated lftp: LFTP | Version 4.6.3a. Anyway, thanks for sharing the command line!
