### ISSUE TITLE
Privacy Badger does not like shields

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#26]
So i have tried to place shields on http://www.darktable.org/resources/camera-support/
And they are getting blocked by Privacy Badger.

**Comment by andabata** [comment]
https://raw.pixls.us/button-samples.svg https://raw.pixls.us/button-cameras.svg
do these work propperly ?

**Comment by LebedevRI** [comment]
Still blocked, even after i remove the domain from Privacy Badger

**Comment by LebedevRI** [comment]
happens only when dt.org is used with https

**Comment by patdavid** [comment]
Cross domain svg requests may not work with https.

**Comment by patdavid** [comment]
Just checked dt.org and the badges appear ok, I think?  Is this still an issue?

**Comment by andabata** [comment]
Seems like privacy badger assumes small png/svgs are trackerbeacons. Can't fix this.

**Comment by LebedevRI** [comment]
maybe try asking them?
https://github.com/EFForg/privacybadger
