### ISSUE TITLE
github caches shields

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#27]
If we open the source code for https://github.com/darktable-org/rawspeed/blob/develop/README.md
we can see:
```html
<img src="https://camo.githubusercontent.com/<blurb1>/<blurb2>" alt="raw.pixls.us - the free raw sample archive" data-canonical-src="https://raw.pixls.us/button-cameras.php" style="max-width:100%;">
```
So it caches them. Perhaps some header can be outputted to decrease the cache time?

**Comment by andabata** [comment]
https://raw.pixls.us/button-samples.svg https://raw.pixls.us/button-cameras.svg
do these work propperly ?

**Comment by andabata** [comment]
Hopefully this is fixed now.
