### ISSUE TITLE
I guess we need better explaination of what we do NOT want

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#30]
![screenshot_20170108_140409](https://cloud.githubusercontent.com/assets/88600/21749212/69e869c6-d5ab-11e6-8bd4-db0981240a8e.png)

**Comment by patdavid** [comment]
* No series (multiple shots at different settings).
(eg: no series with different iso/aperture/shutter/wb/lighting - even if it _is_ a picture of color target).
* Lens cap must be off.
* Prefer landscape shots

**Comment by LebedevRI** [comment]
- No series with different iso/aperture/shutter/wb/lighting - even if it is a picture of color target.
- Lens must be mounted onto camera
- Lens cap must be off
- Lens must be focused
- Prefer landscape shots

**Comment by patdavid** [comment]
I think we've got the list done on the blogpost now, closing.
