### ISSUE TITLE
Pentax K-1 also supports APS-C size raw files

### ISSUE THREAD

**Issue by heckflosse** [pixlsus/raw#39]
but that's not mentioned at raw.pixls.us

**Comment by patdavid** [comment]
Should this be listed as this particular camera in the bullet point for Pentax:

* **Pentax:** Both PEF and DNG.

Should be something like:

* **Pentax:** Both PEF and DNG.
    * K-1 both FF and APS-C

?

**Comment by heckflosse** [comment]
@patdavid Don't know. I just wanted to mention (as suggested by @LebedevRI ) that there are two different raw crops (full and aps-c) for Pentax K-1

**Comment by patdavid** [comment]
@heckflosse Yeah, this was mostly a question for @andabata or @LebedevRI.  If there's no consensus in a little bit I'll go ahead and add it.

**Comment by andabata** [comment]
Personaly i would just keep it a bit more general and not specifically naming 1 model.
