### ISSUE TITLE
sony compression

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#44]
http://helpguide.sony.net/ilc/1450/v1/en/print.pdf
says that there is 
```
Compressed:
Records images in compressed RAW format.
Uncompressed:
Records images in uncompressed RAW format. When [Uncompressed] is selected for [
RAW File Type], the file size of the image will be larger than if it were recorded in
compressed RAW format.
```

so `Of the following brands we like to have:` should read `Sony: all the combinations of compression and bitness settings, that is: 12bit-compressed
12bit-uncompressed
14bit-compressed
14bit-uncompressed`

and if possible the compression should be detected, i'm not sure yet which fields that is

**Comment by Beep6581** [comment]
ILCE-7M2:

```
-EXIF:Compression=Sony ARW Compressed
-EXIF:SonyRawFileType=Sony Compressed RAW
-MakerNotes:RAWFileType=Compressed RAW
```

```
-EXIF:Compression=Uncompressed
-EXIF:SonyRawFileType=Sony Uncompressed 14-bit RAW
-MakerNotes:RAWFileType=Uncompressed RAW
```

**Comment by LebedevRI** [comment]
just to be clear, that is exiftool output, not exiv2, right?

**Comment by Beep6581** [comment]
@LebedevRI yes.

**Comment by LebedevRI** [comment]
@andabata can the "so `Of the following brands we like to have:` should read `Sony: all the combinations of compression and bitness settings, that is: 12bit-compressed
12bit-uncompressed
14bit-compressed
14bit-uncompressed`" part be added right away, please? :)
