### ISSUE TITLE
Exif extraction fails on a filename with spaces.

### ISSUE THREAD

**Issue by andabata** [pixlsus/raw#51]

**Comment by LebedevRI** [comment]
Maybe it would indeed be better to rename some files upon upload?

**Comment by andabata** [comment]
Yes, that would be a good solution for new uploads. But it actually exposes a slightly more serious bug. Which has to be fixed anyhow.
January 24, 2017 2:23 PM, "Roman Lebedev"  wrote:
	Maybe it would indeed be better to rename some files upon upload?
