### ISSUE TITLE
Thank you screen fields blank

### ISSUE THREAD

**Issue by Beep6581** [pixlsus/raw#52]
I uploaded a file, the "Thank you!" screen appeared, "Please take a moment to **correct** or fill-in any missing fields below", but the fields were blank. Aren't they supposed to show metadata extracted from the image?

Reproduced using two SONY ILCE-7M2 ARW files and one Blackmagic URSA 4K DNG.

**Comment by andabata** [comment]
This is related to #51

**Comment by andabata** [comment]
fixed
