### ISSUE TITLE
Thank you screen should give confirmation

### ISSUE THREAD

**Issue by Beep6581** [pixlsus/raw#53]
When filling in the fields in the "Thank you!" screen and pressing the "update" button, I get taken back to https://raw.pixls.us/ with no indication of what just happened. Some kind of alert would be nice on success or failure.

**Comment by andabata** [comment]
@patdavid if i add a parameter to the index.html (maybe i should change it to a php), can you make a nice banner with "thank you, it will appear after it is validated" kinda text ?

**Comment by andabata** [comment]
Same mechanism can be used for failed uploads aswell

**Comment by patdavid** [comment]
@andabata Yes, I'd be happy to make a banner - can you offset the server-side logic in a block for me somwhere (and comment it)?  I can make both "Yay - it worked!" and "What did you do, Ray?!"


![](http://www.whatthehellpodcast.com/wp-content/uploads/2016/11/giphy.gif)

**Comment by andabata** [comment]
@patdavid I've added support for a warning banner in the index.php. for now i've added "unwanted" and "thankyou". Only.. i think it needs some proper html sause / english text. Could you look into that ?

**Comment by patdavid** [comment]
Yes, sorry for being afk at the moment! :(  I'm on work travel and banged up.

I'll have a look tomorrow if I'm feeling a little better, should be quick right? :)
