### ISSUE TITLE
perhaps there should be a page with "used by"

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#65]
```
[00:05:36] <kelvie> the thing with that site is that it's unclear who actually uses it
[00:05:50] <kelvie> darktable does via libraw / dcraw / rawspeed / lensfun?
[00:06:05] <LebedevRI> darktable does not use libraw
[00:06:12] <LebedevRI> only rawspeed
[00:06:14] <kelvie> oh, don't know why I assumed it does.
[00:06:21] <LebedevRI> i use it for regression testing of rawspeed
```

so it can be more obvious what it is actually being used for

**Comment by andabata** [comment]
Yes! That's needed.

**Comment by patdavid** [comment]
I can write this page, but will need some information.  What else can we say uses this data?  Should I be focusing some efforts on getting the word out to other projects that the data is there _to_ be used?

**Comment by andabata** [comment]
I think more of a footnote kinda thing. "The repository data is being used by darktable/rawspeed/something/something to improve their functionality" orsomehting like that

**Comment by LebedevRI** [comment]
Gaining new users would be nice too :)

**Comment by andabata** [comment]
maaaaybe rawtherapee is using data as well as i see some requests from @Beep6581 :)

**Comment by Beep6581** [comment]
I use it for RawTherapee's needs.

**Comment by patdavid** [comment]
Just pushed a first try in commit 7ff0fe7f90e5ad2b13d94d33d8d96fa315fed725

**Comment by andabata** [comment]
Fine with me.

**Comment by patdavid** [comment]
Unless there's a problem with the commit, I'm going to close this now.  Please reopen if we need to!
