### ISSUE TITLE
archives

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#68]
Something needs to be done about archive upload.

**Comment by patdavid** [comment]
What needs to be addressed?

**Comment by LebedevRI** [comment]
Simple solution: add one more checkbox above "Choose file" saying something like "this file is a single raw image, not an archive"
More complicated solution would be to additionally check mime type of newly uploaded file, and completely discard (as in, not even add to db) if it is tar/zip/rar/etc

**Comment by paperdigits** [comment]
Can we just request it be a raw file and not zipped in the instructional text, then throw an error if the user tries to upload an archive?

**Comment by andabata** [comment]
I think if we can use some js to block the most common archive formats, and unwanted fileformats (.png / .jpg). That would reduce 'wrong' uploads a lot.

**Comment by andabata** [comment]
We now can add unwanted fileextensions. This should solve *.jpg, *.png *.zip *.rar uploads.
