### ISSUE TITLE
And yet another variant

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#71]
Sony may have full-frame raw, and APS-C crop
https://raw.pixls.us/getfile.php/1581/raw/DSC04125.ARW
https://raw.pixls.us/getfile.php/1582/raw/DSC04126.ARW

At least, the front page should be reworded like:
```diff
-Canon: RAW, mRAW, sRAW.
+Sony: (applicable only to full-frame cameras) both the normal raw, and the APS-C crop.
+Canon: RAW, mRAW, sRAW.
```

**Comment by andabata** [comment]
whoops.. wrong one closed :)

**Comment by andabata** [comment]
Humm. is already done..apperently...
