### ISSUE TITLE
Fuji modes

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#76]
Fujifilm cameras currently has two modes we are interested in: uncompressed and compressed.
Practically all cameras produce uncompressed raws only.
I'm not aware of any EXIF tag that is used to mark comressed raws.
You could do the same thing rawspeed is doing currently: https://github.com/darktable-org/rawspeed/blob/f49c4a09837ba73fe15af956be795841ea09a00f/src/librawspeed/decoders/RafDecoder.cpp#L372-L393

Also, https://raw.pixls.us/, should be appended with:
```
* Fujifilm: Both the old uncompressed RAF and new compressed RAF (if supported).
```

**Comment by andabata** [comment]
I call this done!

**Comment by patdavid** [comment]
@andabata I only implemented the notice on rpu, not the first part.

**Comment by andabata** [comment]
oh crap :)
