### ISSUE TITLE
missingcameradata seems to not work well

### ISSUE THREAD

**Issue by LebedevRI** [pixlsus/raw#82]
https://github.com/darktable-org/rawspeed/commit/8b50aa4fc4b2676938cf54d0c0df461129569558 added
```
	<Camera make="Canon" model="Canon EOS 20Da" supported="unknown-no-samples">
		<ID make="Canon" model="EOS 20Da">Canon EOS 20Da</ID>
	</Camera>
```
there are no RPU samples for it (but there are for `Canon EOS 20D`),
yet https://raw.pixls.us/?missing#repo doesn't list `Canon EOS 20Da`...

**Comment by LebedevRI** [comment]
What is confusing to me, is that i see no regex matching in https://github.com/pixlsus/raw/blob/aa6b8188dbd8351ba022d87f879f749a18bc0a3a/tools/createarchive.php
so i don't quite understand how we can match `20D` as `20Da`.

**Comment by LebedevRI** [comment]
@andabata poke.
@patdavid does anyone else have access to that machine?

**Comment by andabata** [comment]
OUCH! Don't poke me in the eye. I'll try to fix it soon.

**Comment by LebedevRI** [comment]
@andabata thank you for taking a look!

**Comment by andabata** [comment]
@LebedevRI I did deactivate the cronjob for createarchive. As it created an archive to large to be meaningful. Didn't think at that time that it also did other housekeeping jobs. Removed the archivepart. and it should run again.

**Comment by LebedevRI** [comment]
@andabata yay, thank you very much!
